blank_issues_enabled: false
contact_links:
  - name: I have a problem or idea for the application
    url: hhttps://github.com/timmo001/system-bridge/issues
    about: Please use the main repository to create issues for the app.
  - name: I have a question or need support
    url: hhttps://github.com/timmo001/system-bridge/discussions
    about: Please use the discussions area at the main application project for getting help or asking questions.
